# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-15 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('proper_votes', models.IntegerField(default=0)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections2000.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections2000.Candidate')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections2000.District')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='voivodeship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections2000.Voivodeship'),
        ),
        migrations.AddField(
            model_name='commune',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections2000.Constituency'),
        ),
    ]
